input_lvs = [
    {
        'X': (-100_000, 1, 1),
        'name': 'Price',
        'terms': {
            'extremely high': ('trapmf', -100_000, -100_000, -60_000, -40_000),
            'high': ('trapmf', -60_000, -36_000, -24_000, -7_000),
            'medium': ('trapmf', -12_000, -7_000, -3_500, -2_000),
            'low': ('trapmf', -3_500, -2_000, 0, 0)
        }
    },

    {
        'X': (0, 1025, 1),
        'name': 'ROM',
        'terms': {
            'extremely low': ('trapmf', 0, 0, 2, 4),
            'low': ('trapmf', 4, 8, 16, 32),
            'medium': ('trimf', 16, 32, 64),
            'many': ('trapmf', 64, 128, 256, 512),
            'a lot': ('trapmf', 256, 512, 1024, 1024)
        }
    },

    {
        'X': (0, 10_001, 1),
        'name': 'Battery',
        'terms': {
            'low': ('trapmf', 0, 0, 1000, 4000),
            'medium': ('trimf', 3000, 6000, 7000),
            'big': ('trapmf', 5000, 7000, 10_000, 10_000)
        }
    },

    {
        'X': (0, 71, 1),
        'name': 'Camera',
        'terms': {
            'bad': ('trapmf', 0, 0, 4, 8),
            'good': ('trimf', 8, 12, 16),
            'very good': ('trapmf', 15, 20, 25, 35),
            'excellent': ('trapmf', 32, 48, 70, 70)
        }
    }
]

output_lv = {
    'X': (0, 10.1, 0.1),
    'name': 'Smartphone choiсe',
    'terms': {
        'bad': ('trapmf', 0, 0, 3, 4),
        'nearly good': ('trimf', 3, 4, 5),
        'suitable': ('trapmf', 4, 5, 6, 7),
        'very good': ('trimf', 6, 7, 8),
        'excellent': ('trapmf', 8, 9, 10, 10)
    }
}

rule_base = [
(('extremely high', 'extremely low', 'low', 'bad'), 'nearly good'),
(('extremely high', 'extremely low', 'low', 'good'), 'nearly good'),
(('extremely high', 'extremely low', 'low', 'very good'), 'nearly good'),
(('extremely high', 'extremely low', 'low', 'excellent'), 'nearly good'),
(('extremely high', 'extremely low', 'medium', 'bad'), 'nearly good'),
(('extremely high', 'extremely low', 'medium', 'good'), 'nearly good'),
(('extremely high', 'extremely low', 'medium', 'very good'), 'nearly good'),
(('extremely high', 'extremely low', 'medium', 'excellent'), 'suitable'),
(('extremely high', 'extremely low', 'big', 'bad'), 'nearly good'),
(('extremely high', 'extremely low', 'big', 'good'), 'nearly good'),
(('extremely high', 'extremely low', 'big', 'very good'), 'suitable'),
(('extremely high', 'extremely low', 'big', 'excellent'), 'suitable'),
(('extremely high', 'low', 'low', 'bad'), 'nearly good'),
(('extremely high', 'low', 'low', 'good'), 'nearly good'),
(('extremely high', 'low', 'low', 'very good'), 'nearly good'),
(('extremely high', 'low', 'low', 'excellent'), 'nearly good'),
(('extremely high', 'low', 'medium', 'bad'), 'nearly good'),
(('extremely high', 'low', 'medium', 'good'), 'nearly good'),
(('extremely high', 'low', 'medium', 'very good'), 'suitable'),
(('extremely high', 'low', 'medium', 'excellent'), 'suitable'),
(('extremely high', 'low', 'big', 'bad'), 'nearly good'),
(('extremely high', 'low', 'big', 'good'), 'suitable'),
(('extremely high', 'low', 'big', 'very good'), 'suitable'),
(('extremely high', 'low', 'big', 'excellent'), 'suitable'),
(('extremely high', 'medium', 'low', 'bad'), 'nearly good'),
(('extremely high', 'medium', 'low', 'good'), 'nearly good'),
(('extremely high', 'medium', 'low', 'very good'), 'nearly good'),
(('extremely high', 'medium', 'low', 'excellent'), 'suitable'),
(('extremely high', 'medium', 'medium', 'bad'), 'nearly good'),
(('extremely high', 'medium', 'medium', 'good'), 'suitable'),
(('extremely high', 'medium', 'medium', 'very good'), 'suitable'),
(('extremely high', 'medium', 'medium', 'excellent'), 'suitable'),
(('extremely high', 'medium', 'big', 'bad'), 'suitable'),
(('extremely high', 'medium', 'big', 'good'), 'suitable'),
(('extremely high', 'medium', 'big', 'very good'), 'suitable'),
(('extremely high', 'medium', 'big', 'excellent'), 'suitable'),
(('extremely high', 'many', 'low', 'bad'), 'nearly good'),
(('extremely high', 'many', 'low', 'good'), 'nearly good'),
(('extremely high', 'many', 'low', 'very good'), 'suitable'),
(('extremely high', 'many', 'low', 'excellent'), 'suitable'),
(('extremely high', 'many', 'medium', 'bad'), 'nearly good'),
(('extremely high', 'many', 'medium', 'good'), 'suitable'),
(('extremely high', 'many', 'medium', 'very good'), 'suitable'),
(('extremely high', 'many', 'medium', 'excellent'), 'suitable'),
(('extremely high', 'many', 'big', 'bad'), 'suitable'),
(('extremely high', 'many', 'big', 'good'), 'suitable'),
(('extremely high', 'many', 'big', 'very good'), 'suitable'),
(('extremely high', 'many', 'big', 'excellent'), 'very good'),
(('extremely high', 'a lot', 'low', 'bad'), 'nearly good'),
(('extremely high', 'a lot', 'low', 'good'), 'suitable'),
(('extremely high', 'a lot', 'low', 'very good'), 'suitable'),
(('extremely high', 'a lot', 'low', 'excellent'), 'suitable'),
(('extremely high', 'a lot', 'medium', 'bad'), 'suitable'),
(('extremely high', 'a lot', 'medium', 'good'), 'suitable'),
(('extremely high', 'a lot', 'medium', 'very good'), 'suitable'),
(('extremely high', 'a lot', 'medium', 'excellent'), 'suitable'),
(('extremely high', 'a lot', 'big', 'bad'), 'suitable'),
(('extremely high', 'a lot', 'big', 'good'), 'suitable'),
(('extremely high', 'a lot', 'big', 'very good'), 'very good'),
(('extremely high', 'a lot', 'big', 'excellent'), 'very good'),
(('high', 'extremely low', 'low', 'bad'), 'nearly good'),
(('high', 'extremely low', 'low', 'good'), 'nearly good'),
(('high', 'extremely low', 'low', 'very good'), 'nearly good'),
(('high', 'extremely low', 'low', 'excellent'), 'suitable'),
(('high', 'extremely low', 'medium', 'bad'), 'nearly good'),
(('high', 'extremely low', 'medium', 'good'), 'nearly good'),
(('high', 'extremely low', 'medium', 'very good'), 'suitable'),
(('high', 'extremely low', 'medium', 'excellent'), 'suitable'),
(('high', 'extremely low', 'big', 'bad'), 'nearly good'),
(('high', 'extremely low', 'big', 'good'), 'suitable'),
(('high', 'extremely low', 'big', 'very good'), 'suitable'),
(('high', 'extremely low', 'big', 'excellent'), 'suitable'),
(('high', 'low', 'low', 'bad'), 'nearly good'),
(('high', 'low', 'low', 'good'), 'nearly good'),
(('high', 'low', 'low', 'very good'), 'nearly good'),
(('high', 'low', 'low', 'excellent'), 'suitable'),
(('high', 'low', 'medium', 'bad'), 'nearly good'),
(('high', 'low', 'medium', 'good'), 'suitable'),
(('high', 'low', 'medium', 'very good'), 'suitable'),
(('high', 'low', 'medium', 'excellent'), 'suitable'),
(('high', 'low', 'big', 'bad'), 'suitable'),
(('high', 'low', 'big', 'good'), 'suitable'),
(('high', 'low', 'big', 'very good'), 'suitable'),
(('high', 'low', 'big', 'excellent'), 'suitable'),
(('high', 'medium', 'low', 'bad'), 'nearly good'),
(('high', 'medium', 'low', 'good'), 'nearly good'),
(('high', 'medium', 'low', 'very good'), 'suitable'),
(('high', 'medium', 'low', 'excellent'), 'suitable'),
(('high', 'medium', 'medium', 'bad'), 'suitable'),
(('high', 'medium', 'medium', 'good'), 'suitable'),
(('high', 'medium', 'medium', 'very good'), 'suitable'),
(('high', 'medium', 'medium', 'excellent'), 'suitable'),
(('high', 'medium', 'big', 'bad'), 'suitable'),
(('high', 'medium', 'big', 'good'), 'suitable'),
(('high', 'medium', 'big', 'very good'), 'suitable'),
(('high', 'medium', 'big', 'excellent'), 'very good'),
(('high', 'many', 'low', 'bad'), 'nearly good'),
(('high', 'many', 'low', 'good'), 'suitable'),
(('high', 'many', 'low', 'very good'), 'suitable'),
(('high', 'many', 'low', 'excellent'), 'suitable'),
(('high', 'many', 'medium', 'bad'), 'suitable'),
(('high', 'many', 'medium', 'good'), 'suitable'),
(('high', 'many', 'medium', 'very good'), 'suitable'),
(('high', 'many', 'medium', 'excellent'), 'suitable'),
(('high', 'many', 'big', 'bad'), 'suitable'),
(('high', 'many', 'big', 'good'), 'suitable'),
(('high', 'many', 'big', 'very good'), 'very good'),
(('high', 'many', 'big', 'excellent'), 'very good'),
(('high', 'a lot', 'low', 'bad'), 'suitable'),
(('high', 'a lot', 'low', 'good'), 'suitable'),
(('high', 'a lot', 'low', 'very good'), 'suitable'),
(('high', 'a lot', 'low', 'excellent'), 'suitable'),
(('high', 'a lot', 'medium', 'bad'), 'suitable'),
(('high', 'a lot', 'medium', 'good'), 'suitable'),
(('high', 'a lot', 'medium', 'very good'), 'suitable'),
(('high', 'a lot', 'medium', 'excellent'), 'very good'),
(('high', 'a lot', 'big', 'bad'), 'suitable'),
(('high', 'a lot', 'big', 'good'), 'very good'),
(('high', 'a lot', 'big', 'very good'), 'very good'),
(('high', 'a lot', 'big', 'excellent'), 'very good'),
(('medium', 'extremely low', 'low', 'bad'), 'nearly good'),
(('medium', 'extremely low', 'low', 'good'), 'nearly good'),
(('medium', 'extremely low', 'low', 'very good'), 'suitable'),
(('medium', 'extremely low', 'low', 'excellent'), 'suitable'),
(('medium', 'extremely low', 'medium', 'bad'), 'nearly good'),
(('medium', 'extremely low', 'medium', 'good'), 'suitable'),
(('medium', 'extremely low', 'medium', 'very good'), 'suitable'),
(('medium', 'extremely low', 'medium', 'excellent'), 'suitable'),
(('medium', 'extremely low', 'big', 'bad'), 'suitable'),
(('medium', 'extremely low', 'big', 'good'), 'suitable'),
(('medium', 'extremely low', 'big', 'very good'), 'suitable'),
(('medium', 'extremely low', 'big', 'excellent'), 'suitable'),
(('medium', 'low', 'low', 'bad'), 'nearly good'),
(('medium', 'low', 'low', 'good'), 'nearly good'),
(('medium', 'low', 'low', 'very good'), 'suitable'),
(('medium', 'low', 'low', 'excellent'), 'suitable'),
(('medium', 'low', 'medium', 'bad'), 'suitable'),
(('medium', 'low', 'medium', 'good'), 'suitable'),
(('medium', 'low', 'medium', 'very good'), 'suitable'),
(('medium', 'low', 'medium', 'excellent'), 'suitable'),
(('medium', 'low', 'big', 'bad'), 'suitable'),
(('medium', 'low', 'big', 'good'), 'suitable'),
(('medium', 'low', 'big', 'very good'), 'suitable'),
(('medium', 'low', 'big', 'excellent'), 'very good'),
(('medium', 'medium', 'low', 'bad'), 'nearly good'),
(('medium', 'medium', 'low', 'good'), 'suitable'),
(('medium', 'medium', 'low', 'very good'), 'suitable'),
(('medium', 'medium', 'low', 'excellent'), 'suitable'),
(('medium', 'medium', 'medium', 'bad'), 'suitable'),
(('medium', 'medium', 'medium', 'good'), 'suitable'),
(('medium', 'medium', 'medium', 'very good'), 'suitable'),
(('medium', 'medium', 'medium', 'excellent'), 'very good'),
(('medium', 'medium', 'big', 'bad'), 'suitable'),
(('medium', 'medium', 'big', 'good'), 'suitable'),
(('medium', 'medium', 'big', 'very good'), 'very good'),
(('medium', 'medium', 'big', 'excellent'), 'very good'),
(('medium', 'many', 'low', 'bad'), 'suitable'),
(('medium', 'many', 'low', 'good'), 'suitable'),
(('medium', 'many', 'low', 'very good'), 'suitable'),
(('medium', 'many', 'low', 'excellent'), 'suitable'),
(('medium', 'many', 'medium', 'bad'), 'suitable'),
(('medium', 'many', 'medium', 'good'), 'suitable'),
(('medium', 'many', 'medium', 'very good'), 'suitable'),
(('medium', 'many', 'medium', 'excellent'), 'very good'),
(('medium', 'many', 'big', 'bad'), 'suitable'),
(('medium', 'many', 'big', 'good'), 'very good'),
(('medium', 'many', 'big', 'very good'), 'very good'),
(('medium', 'many', 'big', 'excellent'), 'very good'),
(('medium', 'a lot', 'low', 'bad'), 'suitable'),
(('medium', 'a lot', 'low', 'good'), 'suitable'),
(('medium', 'a lot', 'low', 'very good'), 'suitable'),
(('medium', 'a lot', 'low', 'excellent'), 'very good'),
(('medium', 'a lot', 'medium', 'bad'), 'suitable'),
(('medium', 'a lot', 'medium', 'good'), 'suitable'),
(('medium', 'a lot', 'medium', 'very good'), 'very good'),
(('medium', 'a lot', 'medium', 'excellent'), 'very good'),
(('medium', 'a lot', 'big', 'bad'), 'very good'),
(('medium', 'a lot', 'big', 'good'), 'very good'),
(('medium', 'a lot', 'big', 'very good'), 'very good'),
(('medium', 'a lot', 'big', 'excellent'), 'very good'),
(('low', 'extremely low', 'low', 'bad'), 'nearly good'),
(('low', 'extremely low', 'low', 'good'), 'suitable'),
(('low', 'extremely low', 'low', 'very good'), 'suitable'),
(('low', 'extremely low', 'low', 'excellent'), 'suitable'),
(('low', 'extremely low', 'medium', 'bad'), 'suitable'),
(('low', 'extremely low', 'medium', 'good'), 'suitable'),
(('low', 'extremely low', 'medium', 'very good'), 'suitable'),
(('low', 'extremely low', 'medium', 'excellent'), 'suitable'),
(('low', 'extremely low', 'big', 'bad'), 'suitable'),
(('low', 'extremely low', 'big', 'good'), 'suitable'),
(('low', 'extremely low', 'big', 'very good'), 'suitable'),
(('low', 'extremely low', 'big', 'excellent'), 'very good'),
(('low', 'low', 'low', 'bad'), 'nearly good'),
(('low', 'low', 'low', 'good'), 'suitable'),
(('low', 'low', 'low', 'very good'), 'suitable'),
(('low', 'low', 'low', 'excellent'), 'suitable'),
(('low', 'low', 'medium', 'bad'), 'suitable'),
(('low', 'low', 'medium', 'good'), 'suitable'),
(('low', 'low', 'medium', 'very good'), 'suitable'),
(('low', 'low', 'medium', 'excellent'), 'very good'),
(('low', 'low', 'big', 'bad'), 'suitable'),
(('low', 'low', 'big', 'good'), 'suitable'),
(('low', 'low', 'big', 'very good'), 'very good'),
(('low', 'low', 'big', 'excellent'), 'very good'),
(('low', 'medium', 'low', 'bad'), 'suitable'),
(('low', 'medium', 'low', 'good'), 'suitable'),
(('low', 'medium', 'low', 'very good'), 'suitable'),
(('low', 'medium', 'low', 'excellent'), 'suitable'),
(('low', 'medium', 'medium', 'bad'), 'suitable'),
(('low', 'medium', 'medium', 'good'), 'suitable'),
(('low', 'medium', 'medium', 'very good'), 'very good'),
(('low', 'medium', 'medium', 'excellent'), 'very good'),
(('low', 'medium', 'big', 'bad'), 'suitable'),
(('low', 'medium', 'big', 'good'), 'very good'),
(('low', 'medium', 'big', 'very good'), 'very good'),
(('low', 'medium', 'big', 'excellent'), 'very good'),
(('low', 'many', 'low', 'bad'), 'suitable'),
(('low', 'many', 'low', 'good'), 'suitable'),
(('low', 'many', 'low', 'very good'), 'suitable'),
(('low', 'many', 'low', 'excellent'), 'very good'),
(('low', 'many', 'medium', 'bad'), 'suitable'),
(('low', 'many', 'medium', 'good'), 'suitable'),
(('low', 'many', 'medium', 'very good'), 'very good'),
(('low', 'many', 'medium', 'excellent'), 'very good'),
(('low', 'many', 'big', 'bad'), 'very good'),
(('low', 'many', 'big', 'good'), 'very good'),
(('low', 'many', 'big', 'very good'), 'very good'),
(('low', 'many', 'big', 'excellent'), 'very good'),
(('low', 'a lot', 'low', 'bad'), 'suitable'),
(('low', 'a lot', 'low', 'good'), 'suitable'),
(('low', 'a lot', 'low', 'very good'), 'very good'),
(('low', 'a lot', 'low', 'excellent'), 'very good'),
(('low', 'a lot', 'medium', 'bad'), 'suitable'),
(('low', 'a lot', 'medium', 'good'), 'very good'),
(('low', 'a lot', 'medium', 'very good'), 'very good'),
(('low', 'a lot', 'medium', 'excellent'), 'very good'),
(('low', 'a lot', 'big', 'bad'), 'very good'),
(('low', 'a lot', 'big', 'good'), 'very good'),
(('low', 'a lot', 'big', 'very good'), 'very good'),
(('low', 'a lot', 'big', 'excellent'), 'excellent')
]